CREATE TABLE users (
    user_id serial PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    username varchar(50) NOT NULL UNIQUE,
    email varchar(100) NOT NULL UNIQUE,
    age INT NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    verified BOOLEAN DEFAULT FALSE,
    complete_profile BOOLEAN DEFAULT FALSE
);

SELECT * FROM users;
-- TRUNCATE TABLE users RESTART IDENTITY CASCADE;

-- DROP TABLE users;

CREATE TABLE sessions (
    session_id SERIAL PRIMARY KEY,

    user_id INTEGER NOT NULL REFERENCES users(user_id),

    refresh_token_hash TEXT NOT NULL,

    ip_address VARCHAR(45),

    user_agent TEXT,

    is_revoked BOOLEAN DEFAULT FALSE,

    expires_at TIMESTAMP NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

select * from sessions;

-- TRUNCATE TABLE sessions RESTART IDENTITY CASCADE;

CREATE TABLE otps (
    email VARCHAR(100) NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    otpHash TEXT NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

select * from otps;

-- TRUNCATE TABLE otps RESTART IDENTITY CASCADE;

CREATE TABLE profiles (
    id SERIAL PRIMARY KEY,
    user_id INTEGER UNIQUE NOT NULL REFERENCES users(user_id),
    profile_image VARCHAR(255),
    college VARCHAR(150) NOT NULL,
    courses VARCHAR(100) NOT NULL,
    courses_year SMALLINT,
    city VARCHAR(100),
    bio text,
    github_username VARCHAR(200),
    github_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

select * from profiles;
-- TRUNCATE TABLE profiles RESTART IDENTITY CASCADE;

CREATE TABLE skills (
    skill_id SERIAL PRIMARY KEY,
    skill_name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE user_skills (
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    skill_id INTEGER NOT NULL REFERENCES skills(skill_id)
);

select * from user_skills;

-- TRUNCATE TABLE user_skills RESTART IDENTITY CASCADE;

INSERT INTO skills (skill_name)
VALUES
('C'),
('C++'),
('C#'),
('Java'),
('Python'),
('JavaScript'),
('TypeScript'),
('PHP'),
('Go'),
('Rust'),
('Swift'),
('Kotlin'),
('Dart'),
('R'),
('MATLAB'),
('SQL'),
('HTML'),
('CSS'),
('SASS'),
('Bootstrap'),
('Tailwind CSS'),
('Material UI'),
('React'),
('Next.js'),
('Vue.js'),
('Angular'),
('Redux'),
('React Router'),
('Framer Motion'),
('Three.js'),
('Chart.js'),
('Vite'),
('Webpack'),
('Node.js'),
('Express.js'),
('NestJS'),
('Django'),
('Flask'),
('FastAPI'),
('Laravel'),
('Spring Boot'),
('ASP.NET'),
('GraphQL'),
('REST API'),
('Socket.IO'),
('Prisma'),
('JWT'),
('OAuth'),
('MongoDB'),
('MySQL'),
('PostgreSQL'),
('SQLite'),
('Redis'),
('Firebase'),
('Supabase'),
('Oracle Database'),
('SQL Server'),
('MariaDB'),
('Git'),
('GitHub'),
('GitLab'),
('Docker'),
('Kubernetes'),
('Linux'),
('AWS'),
('Azure'),
('Google Cloud'),
('Nginx'),
('CI/CD'),
('GitHub Actions'),
('Vercel'),
('Netlify'),
('Render'),
('DigitalOcean'),
('React Native'),
('Flutter'),
('Android Development'),
('iOS Development'),
('Figma'),
('Adobe XD'),
('Photoshop'),
('Illustrator'),
('Canva'),
('Blender'),
('Adobe Premiere Pro'),
('Adobe After Effects'),
('Wireframing'),
('Prototyping'),
('User Interface Design'),
('User Experience Design'),
('Responsive Design'),
('Graphic Design'),
('Machine Learning'),
('Deep Learning'),
('TensorFlow'),
('PyTorch'),
('Scikit-learn'),
('OpenCV'),
('Pandas'),
('NumPy'),
('Data Analysis'),
('Data Visualization'),
('Power BI'),
('Tableau'),
('Microsoft Excel'),
('Excel VBA'),
('Generative AI'),
('Prompt Engineering'),
('LangChain'),
('OpenAI API'),
('Hugging Face'),
('Computer Vision'),
('Natural Language Processing'),
('Ethical Hacking'),
('Penetration Testing'),
('Network Security'),
('OWASP'),
('Burp Suite'),
('Wireshark'),
('Kali Linux'),
('Metasploit'),
('Cryptography'),
('Jest'),
('Mocha'),
('Cypress'),
('Selenium'),
('Playwright'),
('JUnit'),
('Postman'),
('Agile'),
('Scrum'),
('Jira'),
('Notion'),
('Trello'),
('Microsoft Word'),
('Microsoft PowerPoint'),
('Google Docs'),
('Google Sheets'),
('SEO'),
('SEM'),
('Google Analytics'),
('Google Ads'),
('Meta Ads'),
('Content Writing'),
('Copywriting'),
('Technical Writing'),
('Email Marketing'),
('Social Media Marketing'),
('Digital Marketing'),
('Market Research'),
('Business Analysis'),
('Project Management'),
('Product Management'),
('Accounting'),
('Bookkeeping'),
('GST'),
('Tally'),
('Financial Analysis'),
('Recruitment'),
('Payroll'),
('Employee Relations'),
('Cisco Packet Tracer'),
('CCNA'),
('TCP/IP'),
('Arduino'),
('Raspberry Pi'),
('Embedded C'),
('ESP32'),
('IoT'),
('Blockchain'),
('Unity'),
('Unreal Engine'),
('DaVinci Resolve'),
('CapCut'),
('Video Editing'),
('Communication'),
('Leadership'),
('Teamwork'),
('Problem Solving'),
('Critical Thinking'),
('Time Management'),
('Public Speaking'),
('Adaptability'),
('Creativity'),
('Decision Making'),
('Conflict Resolution'),
('Negotiation'),
('Mentoring'),
('Research'),
('Presentation Skills'),
('Technical Documentation'),
('Open Source Contribution'),
('Code Review'),
('Debugging'),
('API Integration'),
('Microservices'),
('System Design'),
('Software Architecture');